### ISSUE TITLE
Дубли страниц при url с параметром. Выбрать метод решения: 404, 301, rel="canonical"

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#10]
То же самое, что и #6 , но только для всех остальных страниц кроме главной. Сейчас главная редиректит корректно:
1. `http://vodka.deseven.info/?main` -> `http://vodka.deseven.info/` (должен быть 301 вместо 302)
2. `http://vodka.deseven.info/index.php?main` -> `http://vodka.deseven.info/` (должен быть 301 вместо 302)

но остальные страницы все ещё дублируются:
1. `http://vodka.deseven.info/second` (200 OK)
2. `http://vodka.deseven.info/?second` (200 OK)
3. `http://vodka.deseven.info/index.php?second` (200 OK)

а должно быть:
1. `http://vodka.deseven.info/second` (200 OK)
2. `http://vodka.deseven.info/?second` -> `http://vodka.deseven.info/second` (301 MOVED PERMANENTLY)
3. `http://vodka.deseven.info/index.php?second`  -> `http://vodka.deseven.info/second` (301 MOVED PERMANENTLY)

**Comment by deseven** [comment]
Эту проблему не так надо решать. Если включены ЧПУ, то надо просто не реагировать на запросы вида `?name` и отдавать 404, потому что это некорректный урл для текущей конфигурации.

**Comment by deseven** [comment]
Хотя нет, лучше и правда наверное сделать редирект, на случай если кто-то хочет включать и выключать ЧПУ на лету.

**Comment by nikolassharp** [comment]
Я посмотрел, как это сделано на WordPress. Там они вообще не парятся по этому поводу, и одна и та же страница доступна с кодом 200 по куче адресов:
1. /obo-mne (200 OK)
2. /index.php?pagename=obo-mne -> /?pagename=obo-mne (301 MOVED PERMANENTLY)
3. 2. /index.php?posttype=page&pagename=obo-mne -> /?pagename=obo-mne (301 MOVED PERMANENTLY)

**НО!** Во всех случаях на всех страницах присутствует корректный `<link rel="canonical" href="/obo-mne" />`.

Соответственно, это и есть самый верный подход к решению проблемы. Потому что разновидностей url, с которыми может быть запрошена страница, действительно может быть много, и все их учитывать бессмысленно. Лучше решить в пользу присутствующего по умолчанию `<link rel="canonical" href="path" />`, где path будет соответствующий как при включённом ЧПУ, так и при выключенном. Таким образом, даже если включать/выключать ЧПУ на ходу, то canonical скажет поисковой системе, какая версия на данный момент каноническая, и дублей не будет.

**Comment by nikolassharp** [comment]
Хотя тут надо исходить из рационального отношения к возможностям самой CMS... У WordPress трудозатраты на учёт количества возможных вариантов url с параметром, очевидно, больше, чем просто добавить `rel="canonical"`. У вас же система попроще, поэтому приемлемы будут как вариант с 404 (похуже, т.к. нет учёта включения/выключения ЧПУ на ходу), так и вариант с 301 (получше, т.к. есть учёт включения/выключения ЧПУ на ходу).

**Comment by deseven** [comment]
Я сделал сейчас редиректы в обе стороны, в зависимости от значения `clean_urls`. Не знаю есть ли смысл делать вывод главного урл в head, потому что теперь как бы он всегда и так главный.

Я пока не заливал, но можно проверить в демо.

**Comment by nikolassharp** [comment]
Отличная работа! Спасибо!

Сейчас действительно в `rel=canonical` нет смысла, т.к. нет дублей. Url с несуществующими параметрами тоже отрабатывают корректно `http://vodka.deseven.info/second?customvar=test` (404)

Но всё ещё остаётся вопрос с дубляжом для адресов с `/index.php?`: `http://vodka.deseven.info/index.php?second`. Связано с #11

**Comment by deseven** [comment]
Да, про index.php, я по-прежнему против того, чтобы форсировать редирект на уровне движка. Потому что задумка такая - юзер подключает класс и работает с ним. Если он хочет, чтобы у него что-то открывалось по урлу вида `/mycoolsite.php?mycoolpage`, а его вместо этого будет кидать в корень, то это как минимум некрасиво, а как максимум непонятно.

Я в ридми приведу пример как сделать подобный редирект со стороны веб-сервера, но в движок это включать не хочу.

**Comment by deseven** [comment]
Тем не менее рабочие урлы вида `/index.php?second` при включенном `clean_urls` это косяк, починил.

**Comment by deseven** [comment]
После двухчасового забега в попытках разобраться со всеми этими редиректами, я понял, почему многие движки предпочитают иметь в конфиге параметр базового URL.
Для меня это не вариант, поэтому я пришел к решению отказаться от урлов вида `?name` полностью, т.к. у меня нет времени на тестирование аж четырех вариантов:
1. Движок в корне сайта с `clean_urls = true`
2. Движок в отдельной директории с `clean_urls = true`
3. Движок в корне сайта с `clean_urls = false`
4. Движок в отдельной директории с `clean_urls = false`
Еще можно помножить это все на 3 вебсервера.

В итоге теперь всегда включены ЧПУ, редирект с имени скрипта выполняется силами движка (за это отвечает параметр `forbid_scriptname`).

На примерах:
http://vodka.deseven.info/second => 200
http://vodka.deseven.info/second/ => 200
http://vodka.deseven.info/?second => 404
http://vodka.deseven.info/index.php?second => 301 на http://vodka.deseven.info/?second => 404
http://vodka.deseven.info/index.php/second => 301 на http://vodka.deseven.info/second => 200

**Comment by deseven** [comment]
Если теперь все ок, то я закрываю #10 и #11.

**Comment by nikolassharp** [comment]
> В итоге теперь всегда включены ЧПУ, редирект с имени скрипта выполняется силами движка (за это отвечает параметр forbid_scriptname).

По-моему приемлемое решение. Я в качестве best practise посматриваю на WordPress, и там редирект с `index.php` -> `/` тоже реализован на уровне движка.

**Comment by nikolassharp** [comment]
Рано закрыли!!! Сейчас пишу развёрнутую инструкцию.

**Comment by deseven** [comment]
Ну я так понял к общему мнению пришли и проблема решена, нет?

**Comment by nikolassharp** [comment]
К сожалению, пока нет. Ещё 5 мин., плз, и будет уже 100% инструкция к действию.

**Comment by deseven** [comment]
Не волнуйтесь, надо - откроем, не надо - закроем :)

**Comment by nikolassharp** [comment]
Также должен извиниться за свою ошибку. Моя цитата из [предыдущего сообщения](https://github.com/deseven/vodka/issues/10#issuecomment-283441534):

> Url с несуществующими параметрами тоже отрабатывают корректно `http://vodka.deseven.info/second?customvar=test` (404)

**совершенно неверна!**

Как раз при **ЛЮБЫХ** кастомных GET-параметрах движок должен возвращать искомую страницу, если такая существует, с кодом (200), при этом без никаких редиректов = не изменяя изначально запрошенный адрес.

Это критически важно, например, когда на сайт льётся контекст или тонко отслеживается аналитика переходов на сайт. В таких случаях ссылки на сайт "метятся" расширенными GET-параметрами, позволяющими точно определять источник перехода, название рекламной компании, другие параметры перехода. Например так выглядит ссылка, позволяющая передать в Google Analytics/Яндекс.Метрику развернутые данные о переходе:

`http://vodka.deseven.info/second?utm_source=Yandex_Direct&utm_medium=cpc&
utm_term=search_query&utm_content=promo1&utm_campaign=yandex_company1`

С этой же целью совершенно любая рекламная система метит ссылки собственными get-параметрами. Наиболее популярными в контекстной рекламе являются gclid (Google Adwords) и yclid (Яндекс.Метрика). При этом часта ситуация, когда при отдаче 404-ого кода по url с get-параметрами в рекламную систему сайт может вообще не добавляться, выдавая ошибку добавления.

Таким образом **любые get-параметры должны оставаться в url** (без редиректов и с кодом 200, если страница существует, или 404, если такой страницы нет). Для поисковиков ситуация с get-параметрами не является очевидной (часто по такой же схеме работают фильтры в, например, интернет-магазинах, и get-параметры меняют содержимое страницы). Поэтому, чтобы исключить неочевидность такого рода, предлагаю сделать `rel=canonical` включенным по умолчанию и всегда выводить в нём основной url-страницы.

> На примерах:
> http://vodka.deseven.info/second => 200
> http://vodka.deseven.info/second/ => 200

здесь надо понимать, что для поисковика это 2 разных адреса (один с trailing slash, другой - без). Поэтому здесь есть 3 пути решения:
1. Захардкодить в движке 1 канонический вариант (либо с trailing slash, либо без), и с неканонических url делать 301 редирект на канонический

> После двухчасового забега в попытках разобраться со всеми этими редиректами, я понял, почему многие движки предпочитают иметь в конфиге параметр базового URL.

2. Всё-таки сделать в конфиге параметры базового url :)
3. Дать примеры соответствующих редиректов в .htaccess, nginx.conf и пусть "сами выбирают"

> http://vodka.deseven.info/?second` => 404

(при `clean_urls = true`) это, получается, должна отдаваться **главная** страница (200) с кастомным get-параметром `second` :) .

> http://vodka.deseven.info/index.php?second => 301 на http://vodka.deseven.info/?second => 404
То же, что и выше. Должно быть:
http://vodka.deseven.info/index.php?second => 301 на http://vodka.deseven.info/?second => выводится контент главной страницы (200), в url которой просто так фигурирует кастомный get-параметр `second`. При этом rel="canonical" в коде главной страницы снимает неоднозначности для поисковика.

> http://vodka.deseven.info/index.php/second => 301 на http://vodka.deseven.info/second => 200
Верно!

**Comment by deseven** [comment]
> Это критически важно, например, когда на сайт льётся контекст или тонко отслеживается аналитика переходов на сайт.

Когда я писал первоначальную логику, основная идея была - максимально чистые URL, то есть чтобы юзер видел в адресной строке только название страницы, а не кучу непонятных служебных GET параметров. С формами просто - шлем их в POST, это нормальная практика. С аналитикой, видимо, так не получится? Переделать это не проблема, но неужели мы живем в 2017 году и никто не озаботился передачей служебной инфы другими каналами?

`rel=canonical` я смогу добавить и без указания базового урла, без проблем.

> здесь надо понимать, что для поисковика это 2 разных адреса (один с trailing slash, другой - без)

А это уже мой косяк. Не знаю почему вдруг я понял, что поисковики это считают одной страницей, если в #12 написано обратное. Исправлю.

Я полагаю, что каноническим именем будет то имя, которое написано в `name`, это логично. И в зависимости от того, есть там в конце слеш или нет, будет происходить 301 на каноническое имя.

**Comment by nikolassharp** [comment]
> С формами просто - шлем их в POST, это нормальная практика.

Это не особо касается нашего случая, т.к. flat-file CMS вряд ли кто возьмёт для интернет-магазина, но всё же опишу иную практику. В интернет-магазинах, в частности, работает логика, что надо дать пользователю возможность отфильтровать интересующие его товары, и отфильтрованную выборку отправить, например, другу. Естественно, самый простой способ такой фильтрации и отправки другу - через get-параметры url. Чтобы пользователь просто скопировал и отправил ссылку. А вопросы с поисковиками в такой ситуации решаются уже на месте в зависимости от ситуации.

`С аналитикой, видимо, так не получится?`

К сожалению, никак. Вот как это выглядит:
![image](https://cloud.githubusercontent.com/assets/6283482/23583149/95ee809a-0144-11e7-964d-9b2fb821767a.png)

> Я полагаю, что каноническим именем будет то имя, которое написано в name, это логично. И в зависимости от того, есть там в конце слеш или нет, будет происходить 301 на каноническое имя.

Так даже круче предложенных мною вариантов! Намного!

**Comment by deseven** [comment]
Ок, спасибо за разъяснения. Тогда сделаю поддержку GET параметров, добавлю `rel=canonical` и разберусь со слешами.

**Comment by nikolassharp** [comment]
[Is Vodka SEO friendly?](https://github.com/deseven/vodka/wiki/Is-Vodka-SEO-friendly%3F) :1st_place_medal:

**Comment by deseven** [comment]
Спасибо! Я думал заняться документацией, но пока не нашел на это времени.

**Comment by deseven** [comment]
GET запросы уже должны работать, можно проверить так:
http://dev.vodka.deseven.info/params_test?key1=value1&key2=value2

**Comment by deseven** [comment]
> Тогда сделаю поддержку GET параметров, добавлю rel=canonical и разберусь со слешами.

Это все сделано, но надо проверить.

`base_url` для сайта все же добавил, чтобы исключить неверное настроенные веб-сервера, когда сайт может открываться еще и по другому адресу или даже напрямую по айпи сервера. Теперь url в `rel=canonical` это железно и навсегда, не зависит от окружения.

**Comment by deseven** [comment]
Итого:

http://dev.vodka.deseven.info/params_test?key1=value1&key2=value2 => 200 (canonical - http://dev.vodka.deseven.info/params_test)
http://dev.vodka.deseven.info/params_test/?key1=value1&key2=value2 => 301 на http://dev.vodka.deseven.info/params_test?key1=value1&key2=value2 в соответствии с именем страницы

http://vodka.deseven.info/long/path/test => 301 на http://vodka.deseven.info/long/path/test/ в соответствии с именем страницы

**Comment by deseven** [comment]
Кстати, может тогда избавиться от 301 при наличии или отсутствии конечного слеша, если я все же реализовал `rel=canonical`? Во-первых это лишняя логика, во вторых лишний редирект.

**Comment by nikolassharp** [comment]
Шикарная работа!

https://github.com/deseven/vodka/issues/10#issuecomment-284238724 и https://github.com/deseven/vodka/issues/10#issuecomment-284238947 - проверил. Тут всё ОК. Works like a charm. Опробовал также all in one вариант http://vodka.deseven.info/index.php/long/path/test?param1=value1&param2=value2 :) 

> Кстати, может тогда избавиться от 301 при наличии или отсутствии конечного слеша, если я все же реализовал rel=canonical? Во-первых это лишняя логика, во вторых лишний редирект.

Я бы не стал. Хотя проблема с трактовкой для поисковика теперь отсутствует (дублей и проблем в ранжировании "правильного"/"канонического" варианта не будет), но 301 редирект банально вносит **порядок**: практически исключены ситуации, когда кто-то захочет поставить ссылку и скопирует с сайта неканоническую версию url... Потом в системах аналитики 2 варианта страницы будут трактоваться как отдельные (с и без trailing slash), у каждой из них будут свои базы ссылок, что потребует от вебмастера сводить всё вручную и т.д. и т.п. В общем, разные проблемы могут из-за этого быть, которые так с ходу даже не все и учтёшь. А когда строго одна каноническая версия, то на практике потом жизнь будет в 100 раз легче.

**Comment by deseven** [comment]
Ок, тогда оставляю. Теперь можно закрывать это и #12?

**Comment by nikolassharp** [comment]
Да, однозначно. Фактически все вопросы по роутингу решили в рамках этого issue.

**Comment by deseven** [comment]
Хорошо, спасибо за помощь!

**Comment by deseven** [comment]
Я тут обнаружил небольшой косяк. В меню ссылка на главную страницу генерируется с ее именем, также как и `canonical`. Но при запросе, конечно, происходит 301 на `/`. Насколько это критично с точки зрения SEO и нужно ли это исправлять?

**Comment by nikolassharp** [comment]
Очень критично. Исправить однозначно.

1. canonical для главной должен быть БЕЗ имени страницы. То есть `<link rel="canonical" href="http://site.com/" />`
2. В меню тоже для порядка стоит выводить url главной без имени.
