### ISSUE TITLE
Безопасность. Фильтруются/экранируются ли все GET-параметры?

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#13]
Фильтруются/экранируются ли принимаемые от пользователей параметры в достаточной мере, чтобы 1) не получился доступ на выполнение произвольного PHP кода на сервере и 2) нельзя было вывести в шаблон что захочется (XSS)? Следуете ли вы каким-нибудь best practise в этом отношении? И есть ли вообще критичные в этом плане участки кода кроме роутинга и вывода ссылок в шаблоне? Думаю, в случае flat-file CMS это всё в основном касается использования переменных вроде `$_SERVER` .

https://markjaquith.wordpress.com/2009/09/21/php-server-vars-not-safe-in-forms-or-links/

PS. Сам в этом не силён.

**Comment by deseven** [comment]
Я использую `$_SERVER['PHP_SELF']` и `$_SERVER['REQUEST_URI']` исключительно для редиректов и сравнения с именами страниц, поэтому не генерирую никакой информации на их основе. Единственное место, где косвенно это используется - в генерации url для меню:
`$cur_item = str_replace($this::url,dirname($_SERVER['PHP_SELF']).'/'.$this->pages[$i]['name'],$cur_item);`
Но тут `dirname()` в любом случае должен отбросить все левое, хотя и не мешало бы проверить.

Что касается GET и POST параметров, то я их нигде не испольую и никак не контролирую, это все на усмотрение пользователя.

**Comment by deseven** [comment]
Впрочем чего тут проверять, для безопасности оберну его в банальный `htmlspecialchars()`, [пишут](http://stackoverflow.com/questions/6080022/php-self-and-xss), что этого достаточно.
