### ISSUE TITLE
Docs & examples

### ISSUE THREAD

**Issue by deseven** [deseven/Vodka#14]
Надо определиться с разделами и структурой и обозначить приоритеты в соответствии с важностью. Сейчас есть [офигенная статья по seo-фичам](https://github.com/deseven/vodka/wiki/Is-Vodka-SEO-friendly%3F), но вся "документация" находится в комментариях к демо-версии и на [простенькой странице](http://vodka.deseven.info/usage) а-ля getting started.

Возможно также стоит как-то реорганизовать демо, добавить какие-то наглядные примеры возможностей как на [dev-сайте](http://dev.vodka.deseven.info/).

**Comment by nikolassharp** [comment]
Я думаю, неплохим вариантом (в т.ч. с точки зрения рекламы) в выборе разделов и структуры документации было бы отталкиваться от реальных потребностей целевой аудитории.

Совершенно однозначно нужны минимум 2 варианта:
1. Документация для программистов: тут достаточно честно описать достоинства и недостатки (не надо брать её для инет-магазина :) ) системы, и несколько known approaches, как эффективней всего реализовать что-то на системе. И всё. Остальное они легко посмотрят в единственном классе.
2. Документация для программистов-"любителей", либо непрограммистов вообще. Вот тут нужен творческий подход.

Обычная в таком случае стратегия: 
1. Выделить потребности, которые CMS хорошо закрывает. 

С этой целью в анализ можно попробовать проанализировать её достоинства и недостатки на фоне классических или просто "других" CMS. Например, в достоинства для себя я отношу: всего 1 php класс с минимально необходимой кодовой базов, 1 файл конфига и **единое хранилище всех SEO-тегов в index.php**: для небольших проектов **крайне удобно** управлять всеми SEO-тегами именно из единой "контрольной панели" index.php). 

К недостаткам можно отнести: необходимо знать и понимать, хотя бы минимально, код. Этот недостаток полностью или практически полностью отсекает обычных людей, хотя даже здесь, если сделать "инструкцию по установке" :) в стиле:

> отредактируйте вот этот вот файлик, скачайте Total Commander, нажмите cntr+n и введите адрес вашего сайта, логин и пароль, выделите папочку и нажмите F5 для копирования на ваш хостинг. Наслаждайтесь.

можно спорить и пробовать нести CMS в массу для личных страничек "тётенек" любого уровня знаний.

2. Исходя из выделенных потребностей определить целевую аудиторию, и уже под неё писать examples с соответствующим уровнем детализации.

Так, например, первыми вопросами, которые были у меня, было:
1. Что с SEO?
2. Есть ли разные шаблоны для разных страниц?
3. Есть ли подобие conditional tags
4. Безопасно ли использовать?

Мой сценарий использования: мелкие-средние сайты из нескольких десятков-сотен страниц с неясными перспективами развития, по крайней мере до тех пор, пока эти перспективы не прояснятся. База данных, как и "тяжёлые" CMS с кучей middleware для таких проектов избыточны.

По итогу я описал свои вопросы в Wiki: https://github.com/deseven/vodka/wiki

**Comment by deseven** [comment]
Я не собираюсь ничего никому "продавать" :)
Я просто понимаю, что функционал стал достаточно сложен и обзавелся кучей нюансов, поэтому нужно озаботиться нормальной документацией и примерами. Даже если ты профессиональный кодер, куда приятнее почитать вменяемую документацию, чем идти и ковыряться в исходниках, хоть они и небольшие по объему. Более того, это касается и собственного кода. До текущего этапа разработки, последнее изменение движка было аж полтора года назад и мне пришлось изучать свой же код, потому что я уже банально забыл как именно оно должно работать.

Также, не вижу потребности в мануалах для "обычных людей", потому что для них давно написана куча удобных и простых движков с установкой и настройкой в 2 клика. Конкурировать в данной сфере было бы очень сложно.

Так или иначе, я не особо силен в написании "продающих" статей, какой несомненно является статья про SEO-фичи, поэтому для себя определяю реалистичный план работ так:

1. Переработать демо, добавить туда примеры использования (страница с тестированием какой-либо фичи и ее реализация в коде).
2. Написать вменяемую документацию по всему функционалу.
3. Написать инструкцию по развертке движка на примере демо, включая настройку вебсерверов.
4. Вынести FAQ в вики, откорректировать.

**Comment by nikolassharp** [comment]
По-моему отличный план! В рамках аудитории программистов легко закрывает все их потребности.

**Comment by nikolassharp** [comment]
BTW, совпадение ли, но на почту только что пришла вот такая вот картинка:

![16290-preview-02-58b809249fd0b](https://cloud.githubusercontent.com/assets/6283482/23618917/a0dbb53e-029a-11e7-99a7-6ed8eb58881b.jpg)

Отсюда: https://yellowimages.com/stock/700ml-clear-glass-vodka-bottle-mockup-16290/

:D

**Comment by deseven** [comment]
Думаю я сделал практически все в рамках разумной необходимости. Теперь есть вменяемая документация, несколько гайдов и более наглядное демо. Пока закрываю.
