### ISSUE TITLE
Автоопределение шаблона

### ISSUE THREAD

**Issue by Anatolt** [deseven/vodka#2]
Автоподхват шаблона, если он один

**Comment by deseven** [comment]
В программировании такое называется "undefined behavior" - когда непонятно каким будет результат. Если один шаблон то берем его, ок. Если два то что, выводим ошибку? И при каждом запросе странице лезем проверять сколько у нас там есть шаблонов? Идиотизм какой-то. Тебе никто не мешает собрать свой "дистрибутив" в котором все запихнуть в один файл, прописать нужный шаблон и просто пихать этот один файл куда тебе надо, в дальнейшем обновляя только содержимое class-файла. Хватит заставлять меня делать то, что удобно лично тебе. Найми себе кодера, он напишет такое за пару дней.
