### ISSUE TITLE
Переменные шаблонизатора, если не указаны явно, выводятся в шаблон "как есть"

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#5]
![image](https://cloud.githubusercontent.com/assets/6283482/23444334/1d862432-fe3d-11e6-9c82-16e86c13d113.png)

Для таких переменных стоит сделать одно из двух: 
1. Либо предусмотреть в шаблоне возможность не выводить их и участки кода, с ними связанные, если они не заданы явно. 
2. Либо указать дефолтные значения. Так, например, для {VODKA:CLASS} вполне можно было автоматически генерировать класс для <body> в стиле Wordpress, вроде 'page-' . $pages[$i]["name"]

**Comment by deseven** [comment]
Я думал об этом, но на момент написания не хотел усложнять код дополнительными проверками, потому что подразумевалось, что я буду использовать только те переменные, которые мне действительно нужны.
Но раз уж я и сам при этом накосячил, то это точно нужно сделать.
