### ISSUE TITLE
Страница, выбранная в качестве главной, не должна быть доступна по другим адресам

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#6]
http://home-nadym.ru/vodka/demo/ - главной выбрана pages/main.html
http://home-nadym.ru/vodka/demo/?main - не должна быть доступна, т.к. выбрана главной.

**Comment by deseven** [comment]
А почему нет?

**Comment by nikolassharp** [comment]
Согласно официальным рекомендациям для вебмастеров всех поисковых систем. Это рассматривается как дубли. Она либо не должна быть доступной совсем, либо МОЖЕТ быть доступной, но с указанием обязательного мета-параметра `<meta rel="canonical" href="http://home-nadym.ru/vodka/demo/" />`. При большом количестве дублей сайт может испытывать проблемы с ранжированием.

**Comment by deseven** [comment]
Но в теории ведь этой ссылки нигде и никогда не будет, в поисковую выдачу она не попадет.
Наверное лучшим решением тогда будет сделать 301 на / при запросе главной страницы по ее имени?

**Comment by nikolassharp** [comment]
Всё верно. Нигде и никогда не будет. Но тут есть вероятность такой ситуации. Сайт на вашей CMS каким-то образом вдруг выходит в ТОП и закрепляется там. Начинает мешать конкурентам. Они смотрят, на чём он сделан. Скачивают код вашей CMS и изучают на потенциальные уязвимости, которые могут привести к проблемам с ранжированием. Видят, что есть вот такая вот недокументированная особенность и начинают эксплуатировать её, проставляя ссылки на такие страницы. В результате о таких страницах становится известно поисковым системам, и на сайте появляются дубли -> ранжирование ухудшается. Очень редкая в обычной жизни ситуация, но вполне встречаемая в высококонкурентных коммерческих ТОПах.

Либо 301 редирект на "каноническое" имя страницы (выбранная в качестве основной форма url-адресов), либо 404 на дубли.

То же самое касается и http://vodka.deseven.info/index.php . Если не ошибаюсь, то для этого конкретного файла стандартная практика - 301-редирект на уровне движка, а не .htaccess. Лучше всего глянуть на исходники WordPress.

**Comment by deseven** [comment]
По редиректу с имени главной страницы понятно - он и должен выполняться средствами движка, потому что это имя может быть произвольным.

А вот по редиректу с index.php сложнее - движок написан в виде класса и имя главного файла, куда он подключается, может быть в общем-то любым. Я могу, конечно, проверять имя файла и сравнивать его со строкой запроса, но в каких-то ситуациях это будет очень неочевидным поведением, если в / у нас открывается что-то другое. Думаю конкретно это решение стоит оставить за юзером.

**Comment by deseven** [comment]
К тому же это легко и просто настраивается на любом веб-сервере, не требуя особых знаний.

**Comment by nikolassharp** [comment]
Стоит изменить status code с 302 (found or moved TEMPORARY) на 301 (moved PERMANENTLY). Это напрямую влияет на индексацию айта поисковыми системами. Стандартной практикой для подавляющего большинства случаев является использование именно 301-го, а не 302-го редиректа.

https://www.mattcutts.com/blog/seo-advice-discussing-302-redirects/

> Q: Time out. I’ve got a question. What’s the deal with 302 vs. 301? What does that mean? What’s the difference?
> A: The “302” refers to the HTTP status codes that are returned to your browser when you request a page. For example, a 404 page is called a “404” because web servers return a status code of 404 to indicate that a requested page wasn’t found. The difference between a 301 and a 302 is that a 301 status code means that a page has permanently moved to a new location, while a 302 status code means that a page has temporarily moved to a new location. For example, if you try to fetch a page http://example.com/ and the web server says “That’s a 301. The new location is http://www.example.com/” then the web server is saying “That url you requested? It’s moved permanently to the new location I’m giving you.”

http://www.seoclarity.net/use-301-redirect-vs-302-redirect-15683/
