### ISSUE TITLE
html-версии страниц не должны быть доступны по прямому адресу

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#7]
http://home-nadym.ru/vodka/demo/pages/main.html
http://home-nadym.ru/vodka/demo/pages/sec.html
и т.д. не должны быть доступны

![image](https://cloud.githubusercontent.com/assets/6283482/23444807/def5dd5e-fe3f-11e6-9ef5-ee217358c2d6.png)

**Comment by deseven** [comment]
Это решается только настройкой вебсервера (потому что тут речь об отдаче статики) и я мог бы написать .htaccess, но в наше время уже мало кто использует апач. Наверное стоит описать настройку каждого вебсервера отдельно или хотя бы упомянуть об этом в ридми.

**Comment by deseven** [comment]
Ах ну да, тут уже есть .htaccess, наверное тогда и правда есть смысл правила написать по блокировке статики.
