### ISSUE TITLE
Возможность делать вложенные url-адреса?

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#8]
Будут ли работать такие адреса:
/page1
/page1/subpage
/page1/subpage/subsubpage
/page1/subpage/subsubpage/subsubsubpage

если указывать их в $params["pages"][$i]["name"]?

https://github.com/deseven/vodka/blob/master/vodka.class.php#L183
https://github.com/deseven/vodka/blob/master/vodka.class.php#L238

**Comment by deseven** [comment]
Зависит от настройки вебсервера, но вообще скорее всего должны, я не проверял.

**Comment by nikolassharp** [comment]
Отличная работа! Спасибо!
