### ISSUE TITLE
keywords, description, seoTitle, alternativeH1

### ISSUE THREAD

**Issue by nikolassharp** [deseven/vodka#9]
Кроме стандартного title в параметрах страницы (https://github.com/deseven/vodka/blob/master/demo/config.php#L24) необходимо также иметь возможность задать:
1. **metaKeywords**: `<meta name="keywords" content="SEO, заработок в интернете, WordPress, монетизация, ведение блога, манимейкинг, лайфхак" />`.
2. **metaDescription**: `<meta name="description" content="описание, о чём данная страница" />`.
3. **seoTitle**: если задан, то вместо стандартного `title` страницы выводится именно он. Служит цели более гибкой организации названий в шаблоне. Так, например, стандартный `title` страниц (обычно короткий) может быть использован в меню. При этом `seoTitle` (обычно длинный) будет использован в теге `<title></title>` страницы.
4. **alternativeH1**: если задан, то выводится в `<h1></h1>` страницы вместо стандартного `title`. Используется, когда нужно, чтобы текст в `<h1></h1>` отличался от `title`.

**Comment by deseven** [comment]
1 и 2 реализуются встроенной функцией `$vodka->appendHead()`:
```
$vodka->appendHead('<meta name="keywords" content="SEO, заработок в интернете, WordPress, монетизация, ведение блога, манимейкинг, лайфхак" />');
$vodka->appendHead('<meta name="description" content="описание, о чём данная страница" />');
```

Либо то же самое, но с использованием `replaceVar()`, который также покрывает 3 и 4 пункты. Я не уверен нужно ли это выносить отдельно в конфиг.

**Comment by deseven** [comment]
Наверное все же 1 и 2 есть смысл добавить в конфиг страниц как опциональные параметры.
А вот 3 и 4 лучше оставить на юзера, потому что это очень уж специфично.

**Comment by deseven** [comment]
Теперь можно указывать `description` и `keywords` в конфиге для любой страницы.

**Comment by deseven** [comment]
Появилась такая идея - чтобы угодить всем, но не городить кучу параметров, нужно позволить задавать в конфиге произвольные параметры и на что их менять. Таким образом, конфиг будет выглядеть примерно так:
```
$params["pages"] = [
	[
		"path" => "pages/page.html",
		"title" => "page title",
		"description" => "page description",
		"keywords" => "page keywords",
                "custom" => [
			'{SEOTITLE}' => "seo title",
			'{ALTH1}' => "alternative H1"
                ]
	],
]
```
Возможно также есть смысл эти параметры сделать более приоритетными, чем встроенные в движок, таким образом можно будет переназначать и их тоже.

**Comment by nikolassharp** [comment]
Это шикарная идея!

**Comment by deseven** [comment]
Приоритет кастомных параметров над встроенными оказался плохой идеей, потому что это отличный способ выстрелить себе в ногу, при этом не понимая что вообще происходит и почему оно так работает.
Поэтому от этой части идеи пришлось отказаться, кастомные параметры теперь заменяются после встроенных.
